In [11]:
import numpy as np
A=np.array([[0,1],[2,3],[4,5]])
B=np.array([[0,1,2,3],[4,5,6,7]])
C=np.dot(A,B)
D=C.max()
print(f"行列の積の計算結果は\n{C}\nです。")
print(f"行列の積の最大値は{D}です。")

行列の積の計算結果は
[[ 4  5  6  7]
 [12 17 22 27]
 [20 29 38 47]]
です。
行列の積の最大値は47です。
